//! Declarative macros for the actions system.
//!
//! Three macros for different use cases:
//!
//! - [`declare_actions!`] — Declares action constants and definitions in a library crate.
//!   Use this when definitions need to be shared across crate boundaries (e.g., a cell
//!   library consumed by a desktop app).
//!
//! - [`impl_action_dispatch!`] — Generates a `dispatch_action()` method on an impl type,
//!   referencing constants from a `declare_actions!` module. Use this in binaries where
//!   handler closures reference binary-local types.
//!
//! - [`define_actions!`] — All-in-one macro that generates constants, definitions, AND
//!   handlers in a single declaration. Use this when the library and binary are the same
//!   crate (no cross-crate sharing needed).
//!
//! ## Split pattern (recommended for cells)
//!
//! ```ignore
//! // In lib.rs — shared definitions
//! use actions_proto::declare_actions;
//!
//! declare_actions! {
//!     pub session_actions {
//!         TOGGLE_PLAYBACK = "fts.session.toggle_playback" {
//!             name: "Toggle Playback",
//!             description: "Toggle play/pause state",
//!             category: Transport,
//!             shortcut: "Space",
//!             when: "tab:performance",
//!         }
//!     }
//! }
//! // Generates:
//! //   pub mod session_actions { pub const TOGGLE_PLAYBACK: StaticActionId = ...; pub fn definitions() -> Vec<ActionDefinition>; }
//!
//! // In main.rs — handlers only
//! use actions_proto::impl_action_dispatch;
//!
//! impl_action_dispatch! {
//!     for SessionServiceImpl, use session::session_actions {
//!         TOGGLE_PLAYBACK => handler(self_, cx) {
//!             self_.setlist_service.toggle_playback(cx).await;
//!             ActionResult::success()
//!         }
//!     }
//! }
//! // Generates:
//! //   impl SessionServiceImpl { pub async fn dispatch_action(&self, cx, id) -> Option<ActionResult>; }
//! ```

/// Declare action ID constants and definitions without handlers.
///
/// Use this in library crates to share definitions across crate boundaries.
/// Pair with [`impl_action_dispatch!`] in the binary to add handlers.
///
/// Generates:
/// - A module with `StaticActionId` constants
/// - A `definitions()` function inside the module returning `Vec<ActionDefinition>`
#[macro_export]
macro_rules! declare_actions {
    (
        $(#[$mod_meta:meta])*
        $vis:vis $mod_name:ident {
            $(
                $const_name:ident = $id_str:literal {
                    name: $name:literal,
                    description: $desc:literal,
                    category: $category:ident
                    $(, menu_path: $menu_path:literal )?
                    $(, shortcut: $shortcut:literal )?
                    $(, when: $when:literal )?
                    $(,)?
                }
            )*
        }
    ) => {
        $(#[$mod_meta])*
        $vis mod $mod_name {
            use $crate::ids::StaticActionId;

            $(
                pub const $const_name: StaticActionId = StaticActionId::new($id_str);
            )*

            /// Get all action definitions declared in this module.
            pub fn definitions() -> Vec<$crate::ActionDefinition> {
                vec![
                    $(
                        $crate::ActionDefinition::new(
                            $id_str,
                            $name,
                            $desc,
                        )
                        .with_category($crate::ActionCategory::$category)
                        $(  .with_menu_path($menu_path) )?
                        $(  .with_shortcut($shortcut) )?
                        $(  .with_when($when) )?
                        ,
                    )*
                ]
            }
        }
    };
}

/// Generate a `dispatch_action()` method that routes action IDs to handler bodies.
///
/// Use this in binary crates alongside [`declare_actions!`] in the library.
/// The `use` clause specifies the path to the constants module generated by `declare_actions!`.
///
/// Generates:
/// - `impl Type { pub async fn dispatch_action(&self, cx, id) -> Option<ActionResult> }`
#[macro_export]
macro_rules! impl_action_dispatch {
    (
        for $impl_type:ty, use $mod_path:path {
            $(
                $const_name:ident => handler($self_:ident, $cx:ident) $handler:block
            )*
        }
    ) => {
        impl $impl_type {
            /// Dispatch an action by ID. Returns `None` if the action is not recognized.
            pub async fn dispatch_action(
                &self,
                cx: &::roam::session::Context,
                action_id: &$crate::ActionId,
            ) -> Option<$crate::ActionResult> {
                use $mod_path as __action_ids;
                let __id_str = action_id.as_str();
                $(
                    if __id_str == __action_ids::$const_name.as_str() {
                        let $self_ = self;
                        let $cx = cx;
                        let __result: $crate::ActionResult = { $handler };
                        return Some(__result);
                    }
                )*
                None
            }
        }
    };
}

/// Define actions with co-located metadata and handlers (all-in-one).
///
/// Use this when definitions and handlers live in the same crate and
/// don't need to be shared across crate boundaries. For the split
/// library/binary pattern, use [`declare_actions!`] + [`impl_action_dispatch!`].
///
/// Generates:
/// - A constants module with `StaticActionId` constants and `definitions()` function
/// - `Type::action_definitions() -> Vec<ActionDefinition>` (static method)
/// - `Type::dispatch_action(&self, cx, id) -> Option<ActionResult>` (async method)
#[macro_export]
macro_rules! define_actions {
    (
        $mod_name:ident for $impl_type:ty {
            $(
                $const_name:ident = $id_str:literal {
                    name: $name:literal,
                    description: $desc:literal,
                    category: $category:ident
                    $(, menu_path: $menu_path:literal )?
                    $(, shortcut: $shortcut:literal )?
                    $(, when: $when:literal )?
                    , handler($self_:ident, $cx:ident) $handler:block
                }
            )*
        }
    ) => {
        /// Auto-generated action ID constants.
        pub mod $mod_name {
            use $crate::ids::StaticActionId;

            $(
                pub const $const_name: StaticActionId = StaticActionId::new($id_str);
            )*

            /// Get all action definitions declared in this module.
            pub fn definitions() -> Vec<$crate::ActionDefinition> {
                vec![
                    $(
                        $crate::ActionDefinition::new(
                            $id_str,
                            $name,
                            $desc,
                        )
                        .with_category($crate::ActionCategory::$category)
                        $(  .with_menu_path($menu_path) )?
                        $(  .with_shortcut($shortcut) )?
                        $(  .with_when($when) )?
                        ,
                    )*
                ]
            }
        }

        impl $impl_type {
            /// Get all action definitions declared by this type.
            pub fn action_definitions() -> Vec<$crate::ActionDefinition> {
                $mod_name::definitions()
            }

            /// Dispatch an action by ID. Returns `None` if the action is not recognized.
            pub async fn dispatch_action(
                &self,
                cx: &::roam::session::Context,
                action_id: &$crate::ActionId,
            ) -> Option<$crate::ActionResult> {
                match action_id.as_str() {
                    $(
                        $id_str => {
                            let $self_ = self;
                            let $cx = cx;
                            let result: $crate::ActionResult = { $handler };
                            Some(result)
                        }
                    )*
                    _ => None,
                }
            }
        }
    };
}
